### ISSUE TITLE
What exactly this repository cointains?

### ISSUE THREAD

**Issue by tallero** [ubports/ubuntu-touch-session#13]
Also, does development happen here or on gitlab?

**Comment by UniversalSuperBox** [comment]
This repository contains configuration for making a base Ubuntu install able to start Ubuntu Touch. It includes overrides to default startup files like [apparmor](https://github.com/ubports/ubuntu-touch-session/blob/xenial/apparmor.override) and [lightdm](https://github.com/ubports/ubuntu-touch-session/blob/xenial/lightdm.override) so they start properly. Development happens here.

Ideally, a lot of cleanup would happen on this repository. I think it has some files that need to be removed or redone, but I don't know which those are.
